name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linux:
    name: Test and Package [Linux]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache polserver
        uses: actions/cache@v2
        with:
          path: native/polserver
          key: linux-polserver-a6323c77a

      - name: Upload Polserver
        uses: actions/upload-artifact@v2
        with:
          name: escript-lsp-linux
          path: native/polserver/bin/*
