name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - run: npm install

      - run: npm test

      - run: npx vsce package

      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v2
        with:
          name: escript-lsp
          path: escript-lsp-*.vsix
