name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linux:
    name: Test and Package [Linux]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get polserver HEAD ref
        id: get-ref
        run: |
          echo "ref=$( cd native/polserver && git log -1 --format=%h )" >> $GITHUB_OUTPUT

      - name: Cache polserver
        uses: actions/cache@v3
        with:
          path: native/polserver
          key: linux-polserver-full-${{ steps.get-ref.outputs.ref }}

      - run: npm install

      - run: npm test

      - run: npx vsce package

      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v3
        with:
          name: escript-lsp-linux
          path: escript-lsp-*.vsix

  windows:
    name: Test and Package [Windows]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get polserver HEAD ref
        id: get-ref
        shell: bash
        run: |
          echo "ref=$( cd native/polserver && git log -1 --format=%h )" >> $GITHUB_OUTPUT

      - name: Cache polserver
        uses: actions/cache@v3
        with:
          path: native/polserver
          key: windows-polserver-full-${{ steps.get-ref.outputs.ref }}

      - run: npm install

      - run: npm test

      - run: npx vsce package

      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v3
        with:
          name: escript-lsp-windows
          path: escript-lsp-*.vsix

  mac:
    name: Test and Package [Mac]
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get polserver HEAD ref
        id: get-ref
        run: |
          echo "ref=$( cd native/polserver && git log -1 --format=%h )" >> $GITHUB_OUTPUT

      - name: Cache polserver
        uses: actions/cache@v3
        with:
          path: native/polserver
          key: mac-polserver-full-${{ steps.get-ref.outputs.ref }}

      - name: Set polserver Dependencies
        run: |
          echo "PKG_CONFIG_PATH=/usr/local/opt/openssl@1.1/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - run: npm install

      - run: npm run eslint

      - run: npm test && echo npm run e2e

      - run: npx vsce package

      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v3
        with:
          name: escript-lsp-osx
          path: escript-lsp-*.vsix
