name: Publish
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: robinraju/release-downloader@v1.8
        id: release-download
        with:
            latest: true
            fileName: "*.vsix"

      - name: Publish
        run: echo npx vsce publish -p ${{ secrets.VSCE_PAT }} -i ${{ fromJson(steps.release-download.outputs.downloaded_files)[0] }}
